[package]
name = "tokenizer"
version = "0.1.0"
authors = ["Andrea Moretti <axyzxp@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error = { path = "../error" }
